# Processed: raw_configs/external/General_Config/Kerronex/config.yaml
# Providers: 2 proxy, 24 rule

proxy-groups:
- name: Proxy
  type: select
  proxies:
  - å°æ¹¾æ•…è½¬
  - æ—¥æœ¬æ•…è½¬
  - é¦™æ¸¯è‡ªåŠ¨
  - æ—¥æœ¬è‡ªåŠ¨
  - æ—¥æœ¬èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  icon: https://raw.githubusercontent.com/Mithcell-Ma/icon/refs/heads/main/Manual_Test_Log.png
- name: AI
  type: select
  proxies:
  - ç¾å›½èŠ‚ç‚¹
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/ai.png
- use: &id001
  - s1
  name: å°æ¹¾æ•…è½¬
  type: fallback
  interval: 6
  lazy: true
  url: http://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: false
  filter: (?i)(å°æ¹¾|TW)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/icon/color/asn.png
- use: *id001
  name: æ—¥æœ¬æ•…è½¬
  type: fallback
  interval: 6
  lazy: true
  url: http://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: false
  filter: (?i)(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|æ±äº¬|ä¸œäº¬|JP|japan|tokyo|osaka)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/icon/color/asn.png
- use: *id001
  name: é¦™æ¸¯è‡ªåŠ¨
  type: url-test
  interval: 6
  tolerance: 20
  lazy: true
  url: http://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: false
  filter: (?i)(é¦™æ¸¯|hk|ğŸ‡­ğŸ‡°|hong\s?kong)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/auto.png
- use: *id001
  name: æ—¥æœ¬è‡ªåŠ¨
  type: url-test
  interval: 6
  tolerance: 20
  lazy: true
  url: http://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: false
  filter: (?i)(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|æ±äº¬|ä¸œäº¬|JP|japan|tokyo|osaka)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/auto.png
- use: *id001
  name: YouTube
  hidden: true
  type: select
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
- name: Speedtest
  hidden: true
  type: select
  proxies:
  - DIRECTLY
  - Proxy
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png
- name: Trackerslist
  hidden: true
  type: select
  proxies:
  - DIRECTLY
  - Proxy
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/trackerslist.png
- use: &id002
  - s1
  - s2
  name: ç¾å›½èŠ‚ç‚¹
  type: select
  skip-cert-verify: true
  include-all: true
  filter: (?i)(ğŸ‡ºğŸ‡¸|ç¾å›½|US|united\s?states|america|usa|æ´›æ‰çŸ¶|è¾¾æ‹‰æ–¯|New\s?York|è¥¿é›…å›¾)
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
- use: *id002
  name: æ—¥æœ¬èŠ‚ç‚¹
  type: select
  skip-cert-verify: true
  include-all: true
  filter: (?i)(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|æ±äº¬|ä¸œäº¬|JP|japan|tokyo|osaka)
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
- use: *id002
  name: å…¨éƒ¨èŠ‚ç‚¹
  type: select
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/World_Map.png
  include-all: true
  filter: (?i)^((?!(DIRECTLY|DIRECT|Proxy|Traffic|Expire|Expired|è¿‡æœŸ|å‰©ä½™|æµé‡|å®˜ç½‘|è¶…æ—¶|timeout|å¤±æ•ˆ|Invalid|Test|æµ‹é€Ÿ|æœ¬åœ°|Local)).)*$
- name: æ¼ç½‘ä¹‹é±¼
  type: select
  proxies:
  - DIRECTLY
  - Proxy
  icon: https://testingcf.jsdelivr.net/gh/aihdde/Rules@master/icon/fish.png
rule-providers:
  AWAvenue_Ads_Rule:
    type: http
    behavior: domain
    interval: 86400
    format: yaml
    path: ./ruleset/AWAvenue_Ads_Rule_Clash.yaml
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml
  fake_ip_filter_DustinWin:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/fake_ip_filter_DustinWin.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.mrs
  skk_direct:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./rule-providers/direct.txt
    url: https://ruleset.skk.moe/Clash/non_ip/direct.txt
  global_non_ip:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./rule-providers/global_non_ip.txt
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
  cdn_domainset:
    type: http
    behavior: domain
    interval: 86400
    format: text
    path: ./rule-providers/cdn_domainset.txt
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
  cdn_non_ip:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./rule-providers/cdn_non_ip.txt
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
  domestic_non_ip:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./rule-providers/domestic_non_ip.txt
    url: https://ruleset.skk.moe/Clash/non_ip/domestic.txt
  domestic_ip:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./rule-providers/domestic_ip.txt
    url: https://ruleset.skk.moe/Clash/ip/domestic.txt
  china_ip:
    type: http
    behavior: ipcidr
    interval: 86400
    format: text
    path: ./rule-providers/china_ip.txt
    url: https://ruleset.skk.moe/Clash/ip/china_ip.txt
  china_ip_ipv6:
    type: http
    behavior: ipcidr
    interval: 86400
    format: text
    path: ./rule-providers/china_ip_ipv6.txt
    url: https://ruleset.skk.moe/Clash/ip/china_ip_ipv6.txt
  download_domainset:
    type: http
    behavior: domain
    interval: 86400
    format: text
    url: https://ruleset.skk.moe/Clash/domainset/download.txt
    path: ./rule_set/sukkaw_ruleset/download_domainset.txt
  download_non_ip:
    type: http
    behavior: domain
    interval: 86400
    format: text
    url: https://ruleset.skk.moe/Clash/non_ip/download.txt
    path: ./rule_set/sukkaw_ruleset/download_non_ip.txt
  blackmatrix7_direct:
    type: http
    behavior: domain
    interval: 86400
    format: yaml
    path: ./ruleset/blackmatrix7_direct.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
  private_domain:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/private_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
  cn_domain:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/cn_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
  trackerslist:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/trackerslist.mrs
    url: https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/trackerslist.mrs
  proxy:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/proxy.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/proxy.mrs
  gfw_domain:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/gfw_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs
  ai:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/ai
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs
  youtube_domain:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/youtube_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
  telegram_domain:
    type: http
    behavior: classical
    interval: 86400
    format: yaml
    path: ./ruleset/telegram_domain.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
  telegram_ip:
    type: http
    behavior: ipcidr
    interval: 86400
    format: mrs
    path: ./ruleset/telegram_ip.mrs
    url: https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/telegramip.mrs
  Telegram_No_Resolve:
    type: http
    behavior: classical
    interval: 86400
    format: yaml
    path: ./ruleset/Telegram_No_Resolve.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml
  speedtest_domain:
    type: http
    behavior: domain
    interval: 86400
    format: mrs
    path: ./ruleset/speedtest_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs
rules:
- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),REJECT
- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),REJECT
- DOMAIN-SUFFIX,2022822.xyz,DIRECTLY
- DOMAIN-SUFFIX,download.nvidia.com,DIRECTLY
- RULE-SET,AWAvenue_Ads_Rule,REJECT
- RULE-SET,telegram_ip,Proxy,no-resolve
- RULE-SET,Telegram_No_Resolve,Proxy,no-resolve
- PROCESS-NAME-REGEX,.*telegram.*,Proxy
- RULE-SET,telegram_domain,Proxy
- GEOSITE,private,DIRECT
- GEOSITE,category-public-tracker,DIRECT
- GEOSITE,category-games@cn,DIRECT
- GEOSITE,apple@cn,DIRECT
- GEOSITE,icloud,DIRECT
- GEOSITE,microsoft@cn,DIRECT
- GEOSITE,onedrive,DIRECT
- GEOSITE,microsoft,Proxy
- GEOSITE,telegram,Proxy
- GEOSITE,category-ai-!cn,AI
- GEOIP,telegram,Proxy,no-resolve
- GEOIP,private,DIRECT,no-resolve
- RULE-SET,ai,AI
- RULE-SET,youtube_domain,YouTube
- RULE-SET,speedtest_domain,Speedtest
- RULE-SET,global_non_ip,Proxy
- RULE-SET,skk_direct,DIRECT
- RULE-SET,domestic_non_ip,DIRECT
- RULE-SET,domestic_ip,DIRECT,no-resolve
- RULE-SET,china_ip,DIRECT,no-resolve
- RULE-SET,china_ip_ipv6,DIRECT,no-resolve
- RULE-SET,proxy,Proxy
- RULE-SET,gfw_domain,Proxy
- DOMAIN-SUFFIX,cn,DIRECT
- RULE-SET,blackmatrix7_direct,DIRECTLY
- RULE-SET,trackerslist,Trackerslist
- GEOIP,CN,DIRECT
- MATCH,æ¼ç½‘ä¹‹é±¼
proxy-providers:
  s1:
    type: http
    udp: true
    interval: 86400
    proxy: DIRECTLY
    lazy: true
    health-check: &id003
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
      timeout: 5
      lazy: true
      expected-status: '204'
      method: HEAD
    url: ''
    path: ./proxy_provider/s1.yaml
    override:
      additional-prefix: s1 Â»
  s2:
    type: http
    udp: true
    interval: 86400
    proxy: DIRECTLY
    lazy: true
    health-check: *id003
    url: ''
    path: ./proxy_provider/s2.yaml
    override:
      additional-prefix: s2 Â»
