# Processed: raw_configs/external/General_Config/Lanlan13-14/configfull_lite.yaml
# Providers: 3 proxy, 4 rule

rule-providers:
  emby_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/emby.mrs
  ai_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/ai.mrs
  bilibili_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo-lite/geoip/bilibili.mrs
  fakeip_filter_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/fakeip-filter.mrs
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - æ¬§æ´²èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  - è‡ªå»º/å®¶å®½èŠ‚ç‚¹
  - æ•…éšœè½¬ç§»
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/select.png
- type: select
  proxies: &id001
  - èŠ‚ç‚¹é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - æ¬§æ´²èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  - è‡ªå»º/å®¶å®½èŠ‚ç‚¹
  - å…¨çƒç›´è¿
  name: YouTube
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/youtube.png
- type: select
  proxies: *id001
  name: Google
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/google.png
- type: select
  proxies: *id001
  name: Meta
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/meta.png
- type: select
  proxies: &id002
  - èŠ‚ç‚¹é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - æ¬§æ´²èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  - è‡ªå»º/å®¶å®½èŠ‚ç‚¹
  - å…¨çƒç›´è¿
  include-all: true
  exclude-filter: (?i)(ğŸŸ¢ ç›´è¿)
  name: AI
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/ai.png
- type: select
  proxies: *id001
  name: GitHub
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/github.png
- type: select
  proxies: *id001
  name: OneDrive
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/onedrive.png
- type: select
  proxies: *id001
  name: Microsoft
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/microsoft.png
- type: select
  proxies: *id001
  name: Telegram
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/telegram.png
- type: select
  proxies: *id001
  name: TikTok
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/tiktok.png
- type: select
  proxies: *id001
  name: NETFLIX
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/netflix.png
- type: select
  proxies: *id001
  name: DisneyPlus
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/disney.png
- type: select
  proxies: *id001
  name: HBO
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/hbo.png
- type: select
  proxies: &id003
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - æ¬§æ´²èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  - è‡ªå»º/å®¶å®½èŠ‚ç‚¹
  name: Apple
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/apple.png
- type: select
  proxies: *id002
  include-all: true
  exclude-filter: (?i)(ğŸŸ¢ ç›´è¿)
  name: Emby
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/emby.png
- type: select
  proxies: *id003
  name: å“”å“©å“”å“©
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/bilibili.png
- name: å“”å“©ä¸œå—äºš
  type: select
  proxies:
  - èŠ‚ç‚¹é€‰æ‹©
  - æ–°åŠ å¡èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  - è‡ªå»º/å®¶å®½èŠ‚ç‚¹
  - å…¨çƒç›´è¿
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/bilibilit.png
- name: å·´å“ˆå§†ç‰¹
  type: select
  proxies:
  - å°æ¹¾èŠ‚ç‚¹
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/bahamut.png
- type: select
  proxies: *id001
  name: Spotify
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/spotify.png
- type: select
  proxies: *id003
  name: å›½å†…åª’ä½“
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Chinese_media.png
- type: select
  proxies: *id002
  include-all: true
  exclude-filter: (?i)(ğŸŸ¢ ç›´è¿)
  name: STEAM
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/steam.png
- name: å…¨çƒç›´è¿
  type: select
  proxies:
  - ğŸŸ¢ ç›´è¿
  - ğŸ”— ä»£ç†
  - å…¨éƒ¨èŠ‚ç‚¹
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/direct.png
- name: éšç§æ‹¦æˆª
  type: select
  proxies:
  - ğŸš« æ‹’ç»
  - âšª ä¸¢å¼ƒ
  - ğŸŸ¢ ç›´è¿
  - ğŸ”— ä»£ç†
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/block.png
- type: select
  proxies: *id002
  include-all: true
  exclude-filter: (?i)(ğŸŸ¢ ç›´è¿)
  name: Final
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/final.png
- name: è‡ªå»º/å®¶å®½èŠ‚ç‚¹
  type: select
  include-all: true
  filter: (?=.*(?i)(è‡ªå»º|CF|The_house|private|home|å®¶å®½|hgc|HKT|HKBN|icable|Hinet|att))
  exclude-filter: (?=.*(?i)(Seattle))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/private_node.png
- name: é¦™æ¸¯èŠ‚ç‚¹
  type: select
  proxies:
  - é¦™æ¸¯è‡ªåŠ¨
  - é¦™æ¸¯å‡è¡¡
  include-all: true
  filter: (?=.*(?i)(æ¸¯|hk|hongkong|Hong Kong|ğŸ‡­ğŸ‡°))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Hongkong.png
- name: æ–°åŠ å¡èŠ‚ç‚¹
  type: select
  proxies:
  - æ–°åŠ å¡è‡ªåŠ¨
  - æ–°åŠ å¡å‡è¡¡
  include-all: true
  filter: (?=.*(?i)(æ–°|ğŸ‡¸ğŸ‡¬|SG|singapore))
  exclude-filter: (?=.*(?i)(æ–°è¥¿å…°))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Singapore.png
- name: æ—¥æœ¬èŠ‚ç‚¹
  type: select
  proxies:
  - æ—¥æœ¬è‡ªåŠ¨
  - æ—¥æœ¬å‡è¡¡
  include-all: true
  filter: (?=.*(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Japan.png
- name: å°æ¹¾èŠ‚ç‚¹
  type: select
  proxies:
  - å°æ¹¾è‡ªåŠ¨
  - å°æ¹¾å‡è¡¡
  include-all: true
  filter: (?=.*(?i)(å°|ğŸ‡¹ğŸ‡¼|TW|Taiwan))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/Taiwan_China.png
- name: ç¾å›½èŠ‚ç‚¹
  type: select
  proxies:
  - ç¾å›½è‡ªåŠ¨
  - ç¾å›½å‡è¡¡
  include-all: true
  filter: (?=.*(?i)(ç¾|ğŸ‡ºğŸ‡²|US|America|United States|Los Angeles|Chicago|Ashburn|Seattle|Kansas))
  exclude-filter: (?=.*(?i)(Australia|Russia|RUS))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/America.png
- name: æ¬§æ´²èŠ‚ç‚¹
  type: select
  include-all: true
  filter: (?=.*(?i)(ğŸ‡¦ğŸ‡±|ğŸ‡¦ğŸ‡©|ğŸ‡¦ğŸ‡¹|ğŸ‡§ğŸ‡¾|ğŸ‡§ğŸ‡ª|ğŸ‡§ğŸ‡¦|ğŸ‡§ğŸ‡¬|ğŸ‡­ğŸ‡·|ğŸ‡¨ğŸ‡¾|ğŸ‡¨ğŸ‡¿|ğŸ‡©ğŸ‡°|ğŸ‡ªğŸ‡ª|ğŸ‡«ğŸ‡®|ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|ğŸ‡¬ğŸ‡·|ğŸ‡­ğŸ‡º|ğŸ‡®ğŸ‡¸|ğŸ‡®ğŸ‡ª|ğŸ‡®ğŸ‡¹|ğŸ‡½ğŸ‡°|ğŸ‡±ğŸ‡»|ğŸ‡±ğŸ‡®|ğŸ‡±ğŸ‡¹|ğŸ‡±ğŸ‡º|ğŸ‡²ğŸ‡¹|ğŸ‡²ğŸ‡©|ğŸ‡²ğŸ‡¨|ğŸ‡²ğŸ‡ª|ğŸ‡³ğŸ‡±|ğŸ‡²ğŸ‡°|ğŸ‡³ğŸ‡´|ğŸ‡µğŸ‡±|ğŸ‡µğŸ‡¹|ğŸ‡·ğŸ‡´|ğŸ‡·ğŸ‡º|ğŸ‡¸ğŸ‡²|ğŸ‡·ğŸ‡¸|ğŸ‡¸ğŸ‡°|ğŸ‡¸ğŸ‡®|ğŸ‡ªğŸ‡¸|ğŸ‡¸ğŸ‡ª|ğŸ‡¨ğŸ‡­|ğŸ‡¹ğŸ‡·|ğŸ‡ºğŸ‡¦|ğŸ‡¬ğŸ‡§|ğŸ‡»ğŸ‡¦))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/European.png
- name: å…¨éƒ¨èŠ‚ç‚¹
  type: select
  include-all: true
  tolerance: 20
  interval: 300
  exclude-filter: (?i)(ğŸŸ¢ ç›´è¿)
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/all.png
- type: url-test
  include-all: true
  tolerance: 20
  interval: 300
  max-failed-times: 1
  hidden: true
  name: é¦™æ¸¯è‡ªåŠ¨
  filter: (?=.*(?i)(é¦™æ¸¯|hk|hongkong|Hong Kong|ğŸ‡­ğŸ‡°))
  exclude-filter: (?=.*(?i)(The_HK_automation|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|traffic|plus))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png
- type: url-test
  include-all: true
  tolerance: 20
  interval: 300
  max-failed-times: 1
  hidden: true
  name: æ–°åŠ å¡è‡ªåŠ¨
  filter: (?=.*(?i)(æ–°|ğŸ‡¸ğŸ‡¬|SG|Singapore))
  exclude-filter: (?=.*(?i)(The_SG_automation|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|traffic|plus|æ–°è¥¿å…°))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png
- type: url-test
  include-all: true
  tolerance: 20
  interval: 300
  max-failed-times: 1
  hidden: true
  name: æ—¥æœ¬è‡ªåŠ¨
  filter: (?=.*(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan))
  exclude-filter: (?=.*(?i)(The_JP_automation|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|traffic|plus))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png
- type: url-test
  include-all: true
  tolerance: 20
  interval: 300
  max-failed-times: 1
  hidden: true
  name: å°æ¹¾è‡ªåŠ¨
  filter: (?=.*(?i)(å°|ğŸ‡¹ğŸ‡¼|TW|Taiwan))
  exclude-filter: (?=.*(?i)(The_TW_automation|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|traffic|plus))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png
- type: url-test
  include-all: true
  tolerance: 20
  interval: 300
  max-failed-times: 1
  hidden: true
  name: ç¾å›½è‡ªåŠ¨
  filter: (?=.*(?i)(ç¾|ğŸ‡ºğŸ‡²|US|America|United States|Los Angeles|Chicago|Ashburn|Seattle|Kansas))
  exclude-filter: (?=.*(?i)(The_US_automation|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|russia|austria|plus|traffic|Australia|rus|aus))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/automation2.png
- name: é¦™æ¸¯å‡è¡¡
  type: load-balance
  include-all: true
  strategy: consistent-hashing
  hidden: true
  filter: (?=.*(?i)(é¦™æ¸¯|hk|hongkong|Hong Kong|ğŸ‡­ğŸ‡°))
  exclude-filter: (?=.*(?i)(The_HK_balance|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|traffic|plus))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png
- name: æ–°åŠ å¡å‡è¡¡
  type: load-balance
  include-all: true
  strategy: consistent-hashing
  hidden: true
  filter: (?=.*(?i)(æ–°|ğŸ‡¸ğŸ‡¬|SG|Singapore))
  exclude-filter: (?=.*(?i)(The_SG_balance|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|traffic|plus|æ–°è¥¿å…°))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png
- name: æ—¥æœ¬å‡è¡¡
  type: load-balance
  include-all: true
  strategy: consistent-hashing
  hidden: true
  filter: (?=.*(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan))
  exclude-filter: (?=.*(?i)(The_JP_balance|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|traffic|plus))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png
- name: å°æ¹¾å‡è¡¡
  type: load-balance
  include-all: true
  strategy: consistent-hashing
  hidden: true
  filter: (?=.*(?i)(å°|ğŸ‡¹ğŸ‡¼|TW|Taiwan))
  exclude-filter: (?=.*(?i)(The_TW_balance|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|traffic|plus))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png
- name: ç¾å›½å‡è¡¡
  type: load-balance
  include-all: true
  strategy: consistent-hashing
  hidden: true
  filter: (?=.*(?i)(ç¾|ğŸ‡ºğŸ‡²|US|America|united States|Ashburn|Kansas|Seattle))
  exclude-filter: (?=.*(?i)(The_US_balance|wcloud|0å€|0\.1å€|0\.01å€|0\.3X|0\.2x|0\.5x|3X|2x|1\.5x|russia|austria|plus|traffic|Australia|rus|aus))
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/load-balance.png
- name: æ•…éšœè½¬ç§»
  type: fallback
  include-all: true
  interval: 300
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/fallback.png
- name: ğŸ”— ä»£ç†
  type: select
  hidden: true
  proxies:
  - èŠ‚ç‚¹é€‰æ‹©
- name: ğŸš« æ‹’ç»
  type: select
  hidden: true
  proxies:
  - REJECT
- name: âšª ä¸¢å¼ƒ
  type: select
  hidden: true
  proxies:
  - REJECT-DROP
- name: GLOBAL
  type: select
  include-all: true
  proxies:
  - èŠ‚ç‚¹é€‰æ‹©
  - YouTube
  - Google
  - Meta
  - AI
  - GitHub
  - OneDrive
  - Microsoft
  - Telegram
  - TikTok
  - NETFLIX
  - DisneyPlus
  - HBO
  - Apple
  - Emby
  - å“”å“©å“”å“©
  - å“”å“©ä¸œå—äºš
  - å·´å“ˆå§†ç‰¹
  - Spotify
  - å›½å†…åª’ä½“
  - STEAM
  - å…¨çƒç›´è¿
  - éšç§æ‹¦æˆª
  - Final
  - è‡ªå»º/å®¶å®½èŠ‚ç‚¹
  - é¦™æ¸¯èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - æ¬§æ´²èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  - é¦™æ¸¯è‡ªåŠ¨
  - æ–°åŠ å¡è‡ªåŠ¨
  - æ—¥æœ¬è‡ªåŠ¨
  - å°æ¹¾è‡ªåŠ¨
  - ç¾å›½è‡ªåŠ¨
  - é¦™æ¸¯å‡è¡¡
  - æ–°åŠ å¡å‡è¡¡
  - æ—¥æœ¬å‡è¡¡
  - å°æ¹¾å‡è¡¡
  - ç¾å›½å‡è¡¡
  - æ•…éšœè½¬ç§»
  exclude-filter: (?i)(ğŸŸ¢ ç›´è¿)
  icon: https://pub-8feead0908f649a8b94397f152fb9cba.r2.dev/global.png
proxy-providers:
  Airport_01:
    type: http
    interval: 86400
    health-check: &id004
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    filter: ^(?!.*(æ‹’ç»|ç›´è¿|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|traffic))
    proxy: æ•…éšœè½¬ç§»
    url: è®¢é˜…é“¾æ¥1
    override:
      additional-prefix: '[æœºåœºåç§°1]'
      skip-cert-verify: true
      udp: true
  Airport_02:
    type: http
    interval: 86400
    health-check: *id004
    filter: ^(?!.*(æ‹’ç»|ç›´è¿|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|traffic))
    proxy: æ•…éšœè½¬ç§»
    url: è®¢é˜…é“¾æ¥2
    override:
      additional-prefix: '[æœºåœºåç§°2]'
      skip-cert-verify: true
      udp: true
  Airport_03:
    type: http
    interval: 86400
    health-check: *id004
    filter: ^(?!.*(æ‹’ç»|ç›´è¿|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|traffic))
    proxy: æ•…éšœè½¬ç§»
    url: è®¢é˜…é“¾æ¥3
    override:
      additional-prefix: '[æœºåœºåç§°3]'
      skip-cert-verify: true
      udp: true
rules:
- GEOSITE,category-ads-all,éšç§æ‹¦æˆª
- GEOSITE,private,å…¨çƒç›´è¿
- GEOIP,private,å…¨çƒç›´è¿,no-resolve
- GEOSITE,category-games@cn,å…¨çƒç›´è¿
- GEOSITE,category-public-tracker,å…¨çƒç›´è¿
- GEOSITE,openai,AI
- GEOSITE,category-ai-!cn,AI
- RULE-SET,ai_domain,AI
- GEOSITE,youtube,YouTube
- GEOSITE,google,Google
- GEOIP,google,Google,no-resolve
- GEOSITE,github,GitHub
- GEOSITE,onedrive,OneDrive
- GEOSITE,microsoft,Microsoft
- GEOSITE,apple,Apple
- GEOSITE,telegram,Telegram
- GEOIP,telegram,Telegram,no-resolve
- GEOSITE,facebook,Meta
- GEOSITE,netflix,NETFLIX
- GEOSITE,disney,DisneyPlus
- GEOSITE,hbo,HBO
- RULE-SET,emby_domain,Emby
- GEOSITE,spotify,Spotify
- GEOSITE,bahamut,å·´å“ˆå§†ç‰¹
- GEOSITE,tiktok,TikTok
- GEOSITE,bilibili,å“”å“©å“”å“©
- RULE-SET,bilibili_ip,å“”å“©å“”å“©,no-resolve
- GEOSITE,biliintl,å“”å“©ä¸œå—äºš
- GEOSITE,category-media-cn,å›½å†…åª’ä½“
- GEOSITE,steam,STEAM
- GEOIP,twitter,èŠ‚ç‚¹é€‰æ‹©,no-resolve
- GEOIP,ai,AI,no-resolve
- GEOSITE,gfw,èŠ‚ç‚¹é€‰æ‹©
- GEOSITE,geolocation-!cn,èŠ‚ç‚¹é€‰æ‹©
- GEOSITE,cn,å…¨çƒç›´è¿
- GEOIP,private,å…¨çƒç›´è¿,no-resolve
- GEOIP,cn,å…¨çƒç›´è¿,no-resolve
- MATCH,Final
