# Processed: raw_configs/external/General_Config/Mitchell/config.yaml
# Providers: 4 proxy, 30 rule

rule-providers:
  AWAvenue_Ads_Rule:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    path: ./ruleset/AWAvenue_Ads_Rule_Clash.yaml
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml
  blackmatrix7_ad:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    path: ./ruleset/blackmatrix7_ad.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml
  porn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/category-porn.mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-porn.mrs
  fake_ip_filter_DustinWin:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/fake_ip_filter_DustinWin.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.mrs
  fake_ip_filter_juewuy:
    type: http
    interval: 86400
    behavior: classical
    format: text
    path: ./ruleset/fake_ip_filter_juewuy.list
    url: https://github.com/juewuy/ShellCrash/blob/dev/public/fake_ip_filter.list
  blackmatrix7_direct:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    path: ./ruleset/blackmatrix7_direct.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
  private_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/private_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
  cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/cn_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
  cn_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    path: ./ruleset/cn_ip.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs
  trackerslist:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/trackerslist.mrs
    url: https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/trackerslist.mrs
  proxy:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/proxy.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/proxy.mrs
  gfw_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/gfw_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs
  geolocation-!cn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/geolocation-!cn.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs
  ai:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/ai
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs
  cloudflare:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/cloudflare.mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cloudflare.mrs
  geoip_cloudflare:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    path: ./ruleset/geoip_cloudflare.mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudflare.mrs
  youtube_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/youtube_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
  tiktok_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/tiktok_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs
  netflix_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/netflix_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/netflix.mrs
  disney_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/disney_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/disney.mrs
  geoip_netflix:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    path: ./ruleset/geoip_netflix.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs
  geoip_twitter:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    path: ./ruleset/geoip_twitter.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs
  geoip_facebook:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    path: ./ruleset/geoip_facebook.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs
  telegram_domain:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    path: ./ruleset/telegram_domain.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
  telegram_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    path: ./ruleset/telegram_ip.mrs
    url: https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/telegramip.mrs
  Telegram_No_Resolve:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    path: ./ruleset/Telegram_No_Resolve.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram_No_Resolve.yaml
  apple_cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/apple_cn_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs
  onedrive_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/onedrive_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/onedrive.mrs
  speedtest_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    path: ./ruleset/speedtest_domain.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs
  geoip_cloudfront:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    path: ./ruleset/geoip_cloudfront.mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cloudfront.mrs
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - é¦™æ¸¯æ•…è½¬
  - ç¾å›½æ•…è½¬
  - æ–°åŠ å¡æ•…è½¬
  - é¦™æ¸¯å‡è¡¡åŠ é€Ÿ
  - ç¾å›½å‡è¡¡åŠ é€Ÿ
  - æ–°åŠ å¡å‡è¡¡åŠ é€Ÿ
  - é¦™æ¸¯è‡ªåŠ¨
  - ç¾å›½è‡ªåŠ¨
  - æ–°åŠ å¡è‡ªåŠ¨
  - è‡ªåŠ¨é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  icon: https://raw.githubusercontent.com/Mithcell-Ma/icon/refs/heads/main/Manual_Test_Log.png
- name: AI
  type: select
  proxies:
  - AI_ç¨³å®šèŠ‚ç‚¹
  - AI_è‡ªåŠ¨ä¼˜é€‰
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/ai.png
- use: &id001
  - 2.p2
  - 3.p3
  - 4.p4
  name: AI_ç¨³å®šèŠ‚ç‚¹
  type: fallback
  url: https://cp.cloudflare.com/generate_204
  interval: 7200
  max-failed-times: 1
  tolerance: 100
  lazy: true
  filter: p2 Â»ğŸ‡ºğŸ‡¸ ç¾å›½-03|p2 Â»ğŸ‡¸ğŸ‡¬ ç‹®åŸ-03|p2 Â»ğŸ‡ºğŸ‡¸ ç¾å›½-01
  icon: https://testingcf.jsdelivr.net/gh/aihdde/Rules@master/icon/ai.png
- use: *id001
  name: AI_è‡ªåŠ¨ä¼˜é€‰
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  interval: 3600
  tolerance: 50
  lazy: false
  filter: (?i)(ğŸ‡ºğŸ‡¸|ç¾å›½|ç¾åœ‹|US|united\s?states|america|usa|æ´›æ‰çŸ¶|è¾¾æ‹‰æ–¯|New\s?York|è¥¿é›…å›¾|ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore)
  icon: https://raw.githubusercontent.com/Mithcell-Ma/icon/refs/heads/main/ai_backup.png
- use: *id001
  type: load-balance
  lazy: true
  interval: 600
  strategy: round-robin
  max-failed-times: 3
  name: é¦™æ¸¯å‡è¡¡åŠ é€Ÿ
  filter: (?i)(é¦™æ¸¯|hk|ğŸ‡­ğŸ‡°|hong\s?kong)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/available.png
- use: *id001
  type: load-balance
  lazy: true
  interval: 600
  strategy: round-robin
  max-failed-times: 3
  name: ç¾å›½å‡è¡¡åŠ é€Ÿ
  filter: (?i)(ğŸ‡ºğŸ‡¸|ç¾å›½|ç¾åœ‹|US|united\s?states|america|usa|æ´›æ‰çŸ¶|è¾¾æ‹‰æ–¯|New\s?York|è¥¿é›…å›¾)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/available.png
- use: *id001
  type: load-balance
  lazy: true
  interval: 600
  strategy: round-robin
  max-failed-times: 3
  name: æ–°åŠ å¡å‡è¡¡åŠ é€Ÿ
  filter: (?i)(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore)
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
- use: *id001
  type: fallback
  lazy: true
  interval: 900
  max-failed-times: 3
  tolerance: 100
  name: é¦™æ¸¯æ•…è½¬
  filter: (?i)(é¦™æ¸¯|hk|ğŸ‡­ğŸ‡°|hong\s?kong)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/icon/color/asn.png
- use: *id001
  type: fallback
  lazy: true
  interval: 900
  max-failed-times: 3
  tolerance: 100
  name: ç¾å›½æ•…è½¬
  filter: (?i)(ğŸ‡ºğŸ‡¸|ç¾å›½|ç¾åœ‹|US|united\s?states|america|usa|æ´›æ‰çŸ¶|è¾¾æ‹‰æ–¯|New\s?York|è¥¿é›…å›¾)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/icon/color/asn.png
- use: *id001
  type: fallback
  lazy: true
  interval: 900
  max-failed-times: 3
  tolerance: 100
  name: æ–°åŠ å¡æ•…è½¬
  filter: (?i)(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore)
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
- use: *id001
  name: é¦™æ¸¯è‡ªåŠ¨
  type: url-test
  include-all: false
  tolerance: 100
  interval: 600
  lazy: true
  filter: (?i)(é¦™æ¸¯|hk|ğŸ‡­ğŸ‡°|hong\s?kong)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/auto.png
- use: *id001
  name: ç¾å›½è‡ªåŠ¨
  type: url-test
  include-all: false
  tolerance: 100
  interval: 600
  lazy: true
  filter: (?i)(ğŸ‡ºğŸ‡¸|ç¾å›½|US|united\s?states|america|usa|æ´›æ‰çŸ¶|è¾¾æ‹‰æ–¯|New\s?York|è¥¿é›…å›¾)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/auto.png
- use: *id001
  name: æ–°åŠ å¡è‡ªåŠ¨
  type: url-test
  include-all: false
  tolerance: 100
  interval: 600
  lazy: true
  filter: (?i)(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore)
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/release/icon/color/auto.png
- use: *id001
  name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  url: https://cp.cloudflare.com/generate_204
  include-all: false
  tolerance: 50
  interval: 1800
  lazy: false
  health-check:
    enable: true
    interval: 900
    url: https://cp.cloudflare.com/generate_204
    method: HEAD
    timeout: 5
    expected-status: '204'
  filter: (?i)^((?!(DIRECTLY|DIRECT|Proxy|Traffic|Expire|Expired|è¿‡æœŸ|å‰©ä½™|æµé‡|å®˜ç½‘|è¶…æ—¶|å¤±æ•ˆ|Invalid|Test|æµ‹é€Ÿ|æœ¬åœ°|Local)).)*$
  icon: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/icon/color/urltest.png
- name: TikTok
  type: select
  proxies:
  - ç¾å›½æ•…è½¬
  - ç¾å›½å‡è¡¡åŠ é€Ÿ
  - æ–°åŠ å¡æ•…è½¬
  - æ–°åŠ å¡å‡è¡¡åŠ é€Ÿ
  - ç¾å›½èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png
- type: select
  proxies: &id003
  - Proxy
  - é¦™æ¸¯æ•…è½¬
  - ç¾å›½æ•…è½¬
  - æ–°åŠ å¡æ•…è½¬
  - é¦™æ¸¯å‡è¡¡åŠ é€Ÿ
  - ç¾å›½å‡è¡¡åŠ é€Ÿ
  - æ–°åŠ å¡å‡è¡¡åŠ é€Ÿ
  - é¦™æ¸¯è‡ªåŠ¨
  - ç¾å›½è‡ªåŠ¨
  - æ–°åŠ å¡è‡ªåŠ¨
  - è‡ªåŠ¨é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - å…¨éƒ¨èŠ‚ç‚¹
  - DIRECTLY
  name: YouTube
  hidden: true
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
- name: Speedtest
  hidden: false
  type: select
  proxies:
  - DIRECTLY
  - Proxy
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png
- name: OneDrive
  hidden: true
  type: select
  proxies:
  - DIRECTLY
  - Proxy
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/OneDrive.png
- name: Trackerslist
  hidden: true
  type: select
  proxies:
  - DIRECTLY
  - Proxy
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/trackerslist.png
- use: &id002
  - 1.p1
  - 2.p2
  - 3.p3
  - 4.p4
  name: é¦™æ¸¯èŠ‚ç‚¹
  type: select
  skip-cert-verify: true
  include-all: true
  filter: (?i)(é¦™æ¸¯|hk|ğŸ‡­ğŸ‡°|hong\s?kong)
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
- use: *id002
  name: ç¾å›½èŠ‚ç‚¹
  type: select
  skip-cert-verify: true
  include-all: true
  filter: (?i)(ğŸ‡ºğŸ‡¸|ç¾å›½|US|united\s?states|america|usa|æ´›æ‰çŸ¶|è¾¾æ‹‰æ–¯|New\s?York|è¥¿é›…å›¾)
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
- use: *id002
  name: æ–°åŠ å¡èŠ‚ç‚¹
  type: select
  skip-cert-verify: true
  include-all: true
  filter: (?i)(ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|ç‹®åŸ|SG|Singapore)
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
- use: *id002
  name: æ—¥æœ¬èŠ‚ç‚¹
  type: select
  skip-cert-verify: true
  include-all: true
  filter: (?i)(ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|æ±äº¬|ä¸œäº¬|JP|japan|tokyo|osaka)
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
- use: *id002
  name: å…¨éƒ¨èŠ‚ç‚¹
  type: select
  icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/World_Map.png
  include-all: true
  filter: (?i)^((?!(DIRECTLY|DIRECT|Proxy|Traffic|Expire|Expired|è¿‡æœŸ|å‰©ä½™|æµé‡|å®˜ç½‘|è¶…æ—¶|å¤±æ•ˆ|Invalid|Test|æµ‹é€Ÿ|æœ¬åœ°|Local)).)*$
- type: select
  proxies: *id003
  name: æ¼ç½‘ä¹‹é±¼
  icon: https://testingcf.jsdelivr.net/gh/aihdde/Rules@master/icon/fish.png
proxy-providers:
  1.p1:
    type: http
    udp: true
    interval: 86400
    proxy: DIRECTLY
    lazy: true
    health-check: &id004
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 600
      timeout: 5
      lazy: true
      expected-status: '204'
      method: HEAD
    smux: &id005
      enabled: true
      padding: true
      protocol: smux
    url: ''
    path: ./proxy_provider/p1.yaml
    override:
      additional-prefix: p1 Â»
  2.p2:
    type: http
    udp: true
    interval: 86400
    proxy: DIRECTLY
    lazy: true
    health-check: *id004
    smux: *id005
    url: ''
    path: ./proxy_provider/p2.yaml
    override:
      additional-prefix: p2 Â»
  3.p3:
    type: http
    udp: true
    interval: 86400
    proxy: DIRECTLY
    lazy: true
    health-check: *id004
    smux: *id005
    url: ''
    path: ./proxy_provider/p3.yaml
    override:
      additional-prefix: p3 Â»
  4.p4:
    type: http
    udp: true
    interval: 86400
    proxy: DIRECTLY
    lazy: true
    health-check: *id004
    smux: *id005
    url: ''
    path: ./proxy_provider/p4.yaml
    override:
      additional-prefix: p4 Â»
rules:
- RULE-SET,AWAvenue_Ads_Rule,REJECT
- RULE-SET,blackmatrix7_ad,REJECT
- RULE-SET,porn,REJECT
- RULE-SET,cn_ip,DIRECTLY,no-resolve
- RULE-SET,telegram_ip,Proxy,no-resolve
- RULE-SET,Telegram_No_Resolve,Proxy,no-resolve
- RULE-SET,geoip_cloudflare,AI,no-resolve
- RULE-SET,geoip_cloudfront,DIRECTLY,no-resolve
- RULE-SET,geoip_facebook,Proxy,no-resolve
- RULE-SET,geoip_netflix,Proxy,no-resolve
- RULE-SET,geoip_twitter,Proxy,no-resolve
- DOMAIN-SUFFIX,julebu.co,DIRECTLY
- RULE-SET,blackmatrix7_direct,DIRECTLY
- RULE-SET,private_domain,DIRECTLY
- RULE-SET,cn_domain,DIRECTLY
- RULE-SET,apple_cn_domain,DIRECTLY
- DOMAIN-SUFFIX,lingq.com,AI
- DOMAIN-SUFFIX,youglish.com,AI
- DOMAIN-SUFFIX,deepl.com,AI
- DOMAIN-SUFFIX,chat.openai.com,AI
- DOMAIN-SUFFIX,grammarly.com,AI
- DOMAIN-KEYWORD,sci-hub,AI
- RULE-SET,ai,AI
- RULE-SET,youtube_domain,YouTube
- RULE-SET,tiktok_domain,TikTok
- RULE-SET,netflix_domain,Proxy
- RULE-SET,disney_domain,Proxy
- RULE-SET,onedrive_domain,OneDrive
- RULE-SET,speedtest_domain,Speedtest
- RULE-SET,telegram_domain,Proxy
- RULE-SET,gfw_domain,Proxy
- RULE-SET,geolocation-!cn,Proxy
- RULE-SET,proxy,Proxy
- RULE-SET,trackerslist,Trackerslist
- MATCH,æ¼ç½‘ä¹‹é±¼
