# Processed: raw_configs/local/cleaner_config/dustinwin_ruleset_config.yaml
# Providers: 2 proxy, 14 rule

rule-providers:
  ads:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/ads.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ads.mrs
    interval: 86400
  private:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/private.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/private.mrs
    interval: 86400
  trackerslist:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/trackerslist.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/trackerslist.mrs
    interval: 86400
  microsoft-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/microsoft-cn.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/microsoft-cn.mrs
    interval: 86400
  apple-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/apple-cn.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/apple-cn.mrs
    interval: 86400
  google-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/google-cn.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/google-cn.mrs
    interval: 86400
  games-cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/games-cn.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/games-cn.mrs
    interval: 86400
  ai:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/ai.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/ai.mrs
    interval: 86400
  networktest:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/networktest.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/networktest.mrs
    interval: 86400
  proxy:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/proxy.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/proxy.mrs
    interval: 86400
  cn:
    type: http
    behavior: domain
    format: mrs
    path: ./ruleset/cn.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cn.mrs
    interval: 86400
  privateip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/privateip.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/privateip.mrs
    interval: 86400
  cnip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/cnip.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cnip.mrs
    interval: 86400
  telegramip:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./ruleset/telegramip.mrs
    url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/telegramip.mrs
    interval: 86400
rules:
- RULE-SET,private,ç§æœ‰ç½‘ç»œ
- RULE-SET,trackerslist,Trackerslist
- RULE-SET,microsoft-cn,å¾®è½¯æœåŠ¡
- RULE-SET,apple-cn,è‹¹æœæœåŠ¡
- RULE-SET,google-cn,è°·æ­ŒæœåŠ¡
- RULE-SET,games-cn,æ¸¸æˆæœåŠ¡
- RULE-SET,ai,AI å¹³å°
- RULE-SET,networktest,ç½‘ç»œæµ‹è¯•
- RULE-SET,proxy,ä»£ç†åŸŸå
- RULE-SET,cn,ç›´è¿åŸŸå
- RULE-SET,privateip,ç§æœ‰ç½‘ç»œ,no-resolve
- RULE-SET,cnip,ç›´è¿ IP
- RULE-SET,telegramip,ç”µæŠ¥æ¶ˆæ¯,no-resolve
- MATCH,æ¼ç½‘ä¹‹é±¼
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - é¦™æ¸¯èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å…è´¹èŠ‚ç‚¹
  - ğŸ†š vless èŠ‚ç‚¹
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/proxy.png
- name: ç½‘ç»œæµ‹è¯•
  type: select
  proxies:
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å…è´¹èŠ‚ç‚¹
  - ğŸ†š vless èŠ‚ç‚¹
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/networktest.png
- name: AI å¹³å°
  type: select
  proxies:
  - èŠ‚ç‚¹é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å…è´¹èŠ‚ç‚¹
  - ğŸ†š vless èŠ‚ç‚¹
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/ai.png
- name: Trackerslist
  type: select
  proxies:
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/trackerslist.png
- name: æ¸¸æˆæœåŠ¡
  type: select
  proxies:
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/games-cn.png
- name: å¾®è½¯æœåŠ¡
  type: select
  proxies:
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/microsoft-cn.png
- name: è°·æ­ŒæœåŠ¡
  type: select
  proxies:
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/google-cn.png
- name: è‹¹æœæœåŠ¡
  type: select
  proxies:
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/apple-cn.png
- name: ç›´è¿åŸŸå
  type: select
  proxies:
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/cn.png
- name: ç›´è¿ IP
  type: select
  proxies:
  - å…¨çƒç›´è¿
  - èŠ‚ç‚¹é€‰æ‹©
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/cnip.png
- name: ä»£ç†åŸŸå
  type: select
  proxies:
  - èŠ‚ç‚¹é€‰æ‹©
  - å…¨çƒç›´è¿
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/global.png
- name: ç”µæŠ¥æ¶ˆæ¯
  type: select
  proxies:
  - èŠ‚ç‚¹é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å…è´¹èŠ‚ç‚¹
  - ğŸ†š vless èŠ‚ç‚¹
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/telegram.png
- name: ç§æœ‰ç½‘ç»œ
  type: select
  proxies:
  - å…¨çƒç›´è¿
  hidden: true
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/private.png
- name: æ¼ç½‘ä¹‹é±¼
  type: select
  proxies:
  - èŠ‚ç‚¹é€‰æ‹©
  - é¦™æ¸¯èŠ‚ç‚¹
  - å°æ¹¾èŠ‚ç‚¹
  - æ—¥æœ¬èŠ‚ç‚¹
  - æ–°åŠ å¡èŠ‚ç‚¹
  - ç¾å›½èŠ‚ç‚¹
  - å…è´¹èŠ‚ç‚¹
  - ğŸ†š vless èŠ‚ç‚¹
  - å…¨çƒç›´è¿
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/match.png
- name: å…¨çƒç›´è¿
  type: select
  proxies:
  - DIRECT
  hidden: true
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/direct.png
- name: é¦™æ¸¯èŠ‚ç‚¹
  type: load-balance
  strategy: consistent-hashing
  use:
  - ğŸ›« æœºåœºè®¢é˜…
  filter: (?i)(ğŸ‡­ğŸ‡°|æ¸¯|hk|hongkong|hong kong)
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/hongkong.png
- name: å°æ¹¾èŠ‚ç‚¹
  type: load-balance
  strategy: consistent-hashing
  use:
  - ğŸ›« æœºåœºè®¢é˜…
  filter: (?i)(ğŸ‡¹ğŸ‡¼|å°|tw|taiwan|tai wan)
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/taiwan.png
- name: æ—¥æœ¬èŠ‚ç‚¹
  type: load-balance
  strategy: consistent-hashing
  use:
  - ğŸ›« æœºåœºè®¢é˜…
  filter: (?i)(ğŸ‡¯ğŸ‡µ|æ—¥|jp|japan)
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/japan.png
- name: æ–°åŠ å¡èŠ‚ç‚¹
  type: load-balance
  strategy: consistent-hashing
  use:
  - ğŸ›« æœºåœºè®¢é˜…
  filter: (?i)(ğŸ‡¸ğŸ‡¬|æ–°|sg|singapore)
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/singapore.png
- name: ç¾å›½èŠ‚ç‚¹
  type: load-balance
  strategy: consistent-hashing
  use:
  - ğŸ›« æœºåœºè®¢é˜…
  filter: (?i)(ğŸ‡ºğŸ‡¸|ç¾|us|unitedstates|united states)
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/unitedstates.png
- name: å…è´¹èŠ‚ç‚¹
  type: url-test
  tolerance: 100
  use:
  - ğŸ†“ å…è´¹è®¢é˜…
  icon: https://github.com/DustinWin/ruleset_geodata/releases/download/icons/free.png
proxy-providers:
  ğŸ›« æœºåœºè®¢é˜…:
    type: http
    url: https://example.com/xxx/xxx&flag=clash
    path: ./proxies/airport.yaml
    interval: 86400
    filter: (?i)(ğŸ‡­ğŸ‡°|æ¸¯|hk|hongkong|hong kong|ğŸ‡¹ğŸ‡¼|å°|tw|taiwan|tai wan|ğŸ‡¯ğŸ‡µ|æ—¥|jp|japan|ğŸ‡¸ğŸ‡¬|æ–°|sg|singapore|ğŸ‡ºğŸ‡¸|ç¾|us|unitedstates|united
      states)
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  ğŸ†“ å…è´¹è®¢é˜…:
    type: http
    url: https://example.com/xxx/xxx&flag=clash
    path: ./proxies/free.yaml
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
