# Processed: raw_configs/external/Smart_Mode/666OS/OneSmart_Lite_Config.yaml
# Providers: 2 proxy, 19 rule

proxy-groups:
- type: select
  proxies:
  - é¦™æ¸¯æ™ºèƒ½
  - å°æ¹¾æ™ºèƒ½
  - æ—¥æœ¬æ™ºèƒ½
  - ç‹®åŸæ™ºèƒ½
  - éŸ©å›½æ™ºèƒ½
  - ç¾å›½æ™ºèƒ½
  - æ¬§æ´²æ™ºèƒ½
  - æ‰‹åŠ¨é€‰æ‹©
  - ç›´æ¥è¿æ¥
  name: ä¸€é”®æ™ºèƒ½
  icon: https://github.com/666OS/YYDS/raw/main/mihomo/image/mihomo.png
- type: select
  proxies: &id001
  - ä¸€é”®æ™ºèƒ½
  - é¦™æ¸¯æ™ºèƒ½
  - å°æ¹¾æ™ºèƒ½
  - æ—¥æœ¬æ™ºèƒ½
  - ç‹®åŸæ™ºèƒ½
  - éŸ©å›½æ™ºèƒ½
  - ç¾å›½æ™ºèƒ½
  - æ¬§æ´²æ™ºèƒ½
  - æ‰‹åŠ¨é€‰æ‹©
  - ç›´æ¥è¿æ¥
  name: äººå·¥æ™ºèƒ½
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/AI.png
- type: select
  proxies: *id001
  name: ç¤¾äº¤å¹³å°
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/PBS.png
- type: select
  proxies: *id001
  name: å›½é™…åª’ä½“
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/DomesticMedia.png
- type: select
  proxies: *id001
  name: å›½å¤–æµé‡
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Global.png
- type: select
  proxies:
  - ç›´æ¥è¿æ¥
  - ä¸€é”®æ™ºèƒ½
  - é¦™æ¸¯æ™ºèƒ½
  - å°æ¹¾æ™ºèƒ½
  - æ—¥æœ¬æ™ºèƒ½
  - ç‹®åŸæ™ºèƒ½
  - éŸ©å›½æ™ºèƒ½
  - ç¾å›½æ™ºèƒ½
  - æ¬§æ´²æ™ºèƒ½
  - æ‰‹åŠ¨é€‰æ‹©
  name: å›½å†…æµé‡
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/China.png
- type: select
  proxies: *id001
  name: å…œåº•æµé‡
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Final.png
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  include-all: true
  filter: ^(?!.*(DIRECT|ç›´æ¥è¿æ¥|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Clubhouse.png
- name: ç›´æ¥è¿æ¥
  type: select
  proxies:
  - DIRECT
  hidden: true
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Direct.png
- type: smart
  interval: 200
  lazy: true
  url: https://www.google.com/generate_204
  hidden: true
  uselightgbm: true
  name: é¦™æ¸¯æ™ºèƒ½
  filter: ^(?=.*(?i)(æ¸¯|ğŸ‡­ğŸ‡°|HK|Hong|HKG))(?!.*(æ’é™¤1|æ’é™¤2|5x)).*$
  include-all: true
  policy-priority: ä¼˜:2;å¤‡:0.5
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Hong_Kong.png
- type: smart
  interval: 200
  lazy: true
  url: https://www.google.com/generate_204
  hidden: true
  uselightgbm: true
  name: å°æ¹¾æ™ºèƒ½
  filter: ^(?=.*(?i)(å°|ğŸ‡¼ğŸ‡¸|ğŸ‡¹ğŸ‡¼|TW|tai|TPE|TSA|KHH))(?!.*(æ’é™¤1|æ’é™¤2|5x)).*$
  include-all: true
  policy-priority: ä¼˜:2;å¤‡:0.5
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Taiwan.png
- type: smart
  interval: 200
  lazy: true
  url: https://www.google.com/generate_204
  hidden: true
  uselightgbm: true
  name: æ—¥æœ¬æ™ºèƒ½
  filter: ^(?=.*(?i)(æ—¥|ğŸ‡¯ğŸ‡µ|JP|Japan|NRT|HND|KIX|CTS|FUK))(?!.*(æ’é™¤1|æ’é™¤2|5x)).*$
  include-all: true
  policy-priority: ä¼˜:2;å¤‡:0.5
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Japan.png
- type: smart
  interval: 200
  lazy: true
  url: https://www.google.com/generate_204
  hidden: true
  uselightgbm: true
  name: ç‹®åŸæ™ºèƒ½
  filter: ^(?=.*(?i)(å¡|ğŸ‡¸ğŸ‡¬|SG|Sing|SIN|XSP))(?!.*(æ’é™¤1|æ’é™¤2|5x)).*$
  include-all: true
  policy-priority: ä¼˜:2;å¤‡:0.5
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Singapore.png
- type: smart
  interval: 200
  lazy: true
  url: https://www.google.com/generate_204
  hidden: true
  uselightgbm: true
  name: éŸ©å›½æ™ºèƒ½
  filter: ^(?=.*(?i)(éŸ©|ğŸ‡°ğŸ‡·|éŸ“|é¦–å°”|å—æœé²œ|KR|KOR|Korea|South))(?!.*(æ’é™¤1|æ’é™¤2|5x)).*$
  include-all: true
  policy-priority: ä¼˜:2;å¤‡:0.5
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Korea.png
- type: smart
  interval: 200
  lazy: true
  url: https://www.google.com/generate_204
  hidden: true
  uselightgbm: true
  name: ç¾å›½æ™ºèƒ½
  filter: ^(?=.*(?i)(ç¾|ğŸ‡ºğŸ‡¸|US|USA|SJC|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD))(?!.*(æ’é™¤1|æ’é™¤2|5x)).*$
  include-all: true
  policy-priority: ä¼˜:2;å¤‡:0.5
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/United_States.png
- type: smart
  interval: 200
  lazy: true
  url: https://www.google.com/generate_204
  hidden: true
  uselightgbm: true
  name: æ¬§æ´²æ™ºèƒ½
  filter: ^(?=.*(?i)(å¥¥|æ¯”|ä¿|å…‹ç½—åœ°äºš|å¡|æ·|ä¸¹|çˆ±æ²™|èŠ¬|æ³•|å¾·|å¸Œ|åŒˆ|çˆ±å°”|æ„|æ‹‰|ç«‹|å¢|é©¬å…¶å®ƒ|è·|æ³¢|è‘¡|ç½—|æ–¯æ´›ä¼|æ–¯æ´›æ–‡|è¥¿|ç‘|è‹±|ğŸ‡§ğŸ‡ª|ğŸ‡¨ğŸ‡¿|ğŸ‡©ğŸ‡°|ğŸ‡«ğŸ‡®|ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|ğŸ‡®ğŸ‡ª|ğŸ‡®ğŸ‡¹|ğŸ‡±ğŸ‡¹|ğŸ‡±ğŸ‡º|ğŸ‡³ğŸ‡±|ğŸ‡µğŸ‡±|ğŸ‡¸ğŸ‡ª|ğŸ‡¬ğŸ‡§|CDG|FRA|AMS|MAD|BCN|FCO|MUC|BRU))(?!.*(æ’é™¤1|æ’é™¤2|5x)).*$
  include-all: true
  policy-priority: ä¼˜:2;å¤‡:0.5
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/European_Union.png
rule-providers:
  Private:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/Private.mrs
  Direct:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/Direct.mrs
  AI:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/AI.mrs
  Telegram:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/Telegram.mrs
  SocialMedia:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/SocialMedia.mrs
  XPTV:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/XPTV.mrs
  Emby:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/Emby.mrs
  Streaming:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/Streaming.mrs
  Proxy:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/Proxy.mrs
  China:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/domain/China.mrs
  PrivateIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/Private.mrs
  AIIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/AI.mrs
  TelegramIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/Telegram.mrs
  SocialMediaIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/SocialMedia.mrs
  XPTVIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/XPTV.mrs
  EmbyIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/Emby.mrs
  StreamingIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/Streaming.mrs
  ProxyIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/Proxy.mrs
  ChinaIP:
    type: http
    behavior: ipcidr
    format: mrs
    interval: 86400
    url: https://github.com/666OS/rules/raw/release/mihomo/ip/China.mrs
proxy-providers:
  ä¼˜è´¨æœåŠ¡å•†:
    type: http
    interval: 86400
    proxy: DIRECT
    health-check: &id002
      enable: true
      url: https://www.google.com/generate_204
      interval: 300
    filter: ^(?!.*(ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))
    url: ä¼˜è´¨è®¢é˜…æºåœ°å€
    override:
      additional-prefix: '[ä¼˜] '
  å¤‡ç”¨æœåŠ¡å•†:
    type: http
    interval: 86400
    proxy: DIRECT
    health-check: *id002
    filter: ^(?!.*(ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))
    url: å¤‡ç”¨è®¢é˜…æºåœ°å€
    override:
      additional-prefix: '[å¤‡] '
rules:
- AND,((DST-PORT,443),(NETWORK,UDP),(NOT,((GEOIP,CN)))),REJECT
- RULE-SET,Private,ç›´æ¥è¿æ¥
- RULE-SET,Direct,ç›´æ¥è¿æ¥
- RULE-SET,XPTV,ç›´æ¥è¿æ¥
- RULE-SET,AI,äººå·¥æ™ºèƒ½
- RULE-SET,Telegram,ç¤¾äº¤å¹³å°
- RULE-SET,SocialMedia,ç¤¾äº¤å¹³å°
- RULE-SET,Emby,å›½é™…åª’ä½“
- RULE-SET,Streaming,å›½é™…åª’ä½“
- RULE-SET,Proxy,å›½å¤–æµé‡
- RULE-SET,China,å›½å†…æµé‡
- RULE-SET,PrivateIP,ç›´æ¥è¿æ¥,no-resolve
- RULE-SET,XPTVIP,ç›´æ¥è¿æ¥,no-resolve
- RULE-SET,AIIP,äººå·¥æ™ºèƒ½,no-resolve
- RULE-SET,TelegramIP,ç¤¾äº¤å¹³å°,no-resolve
- RULE-SET,SocialMediaIP,ç¤¾äº¤å¹³å°,no-resolve
- RULE-SET,EmbyIP,å›½é™…åª’ä½“,no-resolve
- RULE-SET,StreamingIP,å›½é™…åª’ä½“,no-resolve
- RULE-SET,ProxyIP,å›½å¤–æµé‡,no-resolve
- RULE-SET,ChinaIP,å›½å†…æµé‡
- MATCH,å…œåº•æµé‡
